### ISSUE TITLE
Constructor feature request

### ISSUE THREAD

**Issue by fschon** [downdrown/vaadin-minicalendar#38]
It would be nice to have the following options on the constructor:

1. Available date range (like the Vaadin DatePicker)
2. List of available days
3. List of List of days with List of styles :-)

In my case these are known at construction time and would save the 60 odd server roundtrips.

Thanks for the great component.

**Comment by downdrown** [comment]
Hey @fschon! I do get 1 and 2 (so I think 😅) but you'd need to elaborate on your 3rd suggestion.
Do you wish to have a specific styling for some days?

**Comment by fschon** [comment]
Yes. In my use case, each available day should have a different styling to non available days. So only two different styles necessary - available or not available styles. 

But I thought that maybe someone would have a need for more than one styling option for days, therefore the "list of lists of stylings". So maybe:
-  a list of available styled days
- a list of not available styled days
-  and a list of public holiday styled days. 

Of course some kind of styling priority would have to be defined - maybe last one wins?

Thanks in advance for updating the component.

**Comment by downdrown** [comment]
Hey @fschon, thanks for your suggestions.

I just checked the Vaadin internal `com.vaadin.flow.component.datepicker.DatePicker` but I could not find a constructor allowing you to define the valid range (a.k.a. [setMin(LocalDate)](https://vaadin.com/api/platform/24.3.9/com/vaadin/flow/component/datepicker/DatePicker.html#setMin(java.time.LocalDate)) and [setMax(LocalDate)](https://vaadin.com/api/platform/24.3.9/com/vaadin/flow/component/datepicker/DatePicker.html#setMax(java.time.LocalDate))).
![image](https://github.com/downdrown/vaadin-minicalendar/assets/3913600/a9d12bec-0c9f-4e82-af73-cccf3d2c9f50)

_(As a side note: I updated the AddOn to Vaadin to `24.3.9`)_

`MiniCalendar` provides a `setDayEnabledProvider(SerializablePredicate<LocalDate>)` method to dynamically en- or disable days for selection. This could also be a more complex predicate like the following:

```
miniCalendar.setDayEnabledProvider(date -> 
    date.isAfter(LocalDate.of(2024, Month.APRIL, 1)) && 
    date.isBefore(LocalDate.of(2024, Month.MAY, 1)) &&
    isNoPublicHoliday(date)
);
```

Same goes for adding styles to your days. You can simply use `setDayStyleProvider(SerializableFunction<LocalDate, List<String>>)` to dynamically add (multiple) styles to a certain date:

```
List<LocalDate> publicHolidays = gatherYourLocalHolidays();
miniCalendar.setDayStyleProvider(day -> {
    if (publicHolidays.contains(day)) {
        return List.of("public-holiday", "some-other-spicy-style");
    }
    return null;
});
```

Regarding the public holidays you mentioned I am not quite sure what you mean. Holidays differ by country and there's no easy way (that I know of) to trustworthy check for them using the standard Java LocalDate API. I'd like to not include any 3rd party libraries into the AddOn if not really necessary.

That's the reason I tried to make it quite flexible in the first place.

If your request adresses convenience I can surely provide an additional constructor in which you can directly pass a `dayEnabledProvider` and a `dayStyleProvider`.

Please let me know if this helps you already or if you still need a change 🙂

**Comment by fschon** [comment]
Hi Manfred,

I think you misunderstood my feature request. I know that the existing
implementation is very flexible using the callbacks, but as your
documentation also points out, these callback per rendered day result in 31
callbacks to provide the necessary information, and can be inefficient.

My suggestion was to provide this information at constructor or
initialisation time and so avoid the many callbacks.

In your application you need these to be dynamic across the lifecycle if
the calendar. In my application I already know this information at
construction time.

The holidays example was just an example of the kind of info one might
create a list of to add at construction time. It wasn't a request to
support international holidays.

Hope this helps clarify.
F.

**Comment by downdrown** [comment]
Hey @fschon, thanks for clarification.

I think I understand better what you mean now.
The component does not actually make server roundtrips for the styles to be applied, it happens server side before the component gets "drawn".

I just adapted my showcase sample to add styles to each day and just increment a counter, so that the data is dynamic, see below screen capture:

https://github.com/downdrown/vaadin-minicalendar/assets/3913600/ce62e51a-e979-4851-9c74-2399fe25106b

So if you already have static information about the stylings you wish to apply, you've basically already won.
My warning in the documentation refers to heavy db operations in these callbacks, which is really (_really_) a bad thing to do.
If you e.g. load the data on view creation, store the reference in a local var and use that var in the style provider you should be fine.

If you experience this differently it would be super nice to have a minimalist sample project to play around, or maybe also a short screencast of the roundtrips you're experiencing.

Please don't get me wrong, I'm really not trying to "not do that change" for you, I'm just trying to figure out what the best solution could be 😅 

I also was thinking about adding the actual date as a css class to the span of the days. In this way you could simply inject CSS into your page and you'd also be ready 2 go.

However I'm still debating with myself whether I like this or not 😆

**Comment by fschon** [comment]
Ah, i understand. If there is no client-server roundtrip per day, then the
current implementation is great thanks :-).

**Comment by downdrown** [comment]
Yep, there are no client-server roundtrips per day. The creation of the layout happens server side and before the component gets attached. As I said, it's just not a good idea to have some heavy computation in these callbacks as they can get called quite a few times when you navigate through the calendar.

I'm closing this issue now but please do let me know when you really have some performance issues and see any possible enhancements. 🙂
